// Autogenerated from Pigeon (v15.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class SelectorMessage {
  SelectorMessage({
    this.containsText,
    this.className,
    this.id,
    this.focused,
    this.index,
  });

  String? containsText;

  String? className;

  int? id;

  bool? focused;

  int? index;

  Object encode() {
    return <Object?>[
      containsText,
      className,
      id,
      focused,
      index,
    ];
  }

  static SelectorMessage decode(Object result) {
    result as List<Object?>;
    return SelectorMessage(
      containsText: result[0] as String?,
      className: result[1] as String?,
      id: result[2] as int?,
      focused: result[3] as bool?,
      index: result[4] as int?,
    );
  }
}

class _FlutterTestNativeApiCodec extends StandardMessageCodec {
  const _FlutterTestNativeApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is SelectorMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return SelectorMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterTestNativeApi {
  /// Constructor for [FlutterTestNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterTestNativeApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _FlutterTestNativeApiCodec();

  Future<void> tap(SelectorMessage selector) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.flutter_test_native.FlutterTestNativeApi.tap';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[selector]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}
