// Autogenerated from Pigeon (v15.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package io.flutter.flutter_test_native;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SelectorMessage {
    private @Nullable String containsText;

    public @Nullable String getContainsText() {
      return containsText;
    }

    public void setContainsText(@Nullable String setterArg) {
      this.containsText = setterArg;
    }

    private @Nullable String className;

    public @Nullable String getClassName() {
      return className;
    }

    public void setClassName(@Nullable String setterArg) {
      this.className = setterArg;
    }

    private @Nullable Long id;

    public @Nullable Long getId() {
      return id;
    }

    public void setId(@Nullable Long setterArg) {
      this.id = setterArg;
    }

    private @Nullable Boolean focused;

    public @Nullable Boolean getFocused() {
      return focused;
    }

    public void setFocused(@Nullable Boolean setterArg) {
      this.focused = setterArg;
    }

    private @Nullable Long index;

    public @Nullable Long getIndex() {
      return index;
    }

    public void setIndex(@Nullable Long setterArg) {
      this.index = setterArg;
    }

    public static final class Builder {

      private @Nullable String containsText;

      @CanIgnoreReturnValue
      public @NonNull Builder setContainsText(@Nullable String setterArg) {
        this.containsText = setterArg;
        return this;
      }

      private @Nullable String className;

      @CanIgnoreReturnValue
      public @NonNull Builder setClassName(@Nullable String setterArg) {
        this.className = setterArg;
        return this;
      }

      private @Nullable Long id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@Nullable Long setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable Boolean focused;

      @CanIgnoreReturnValue
      public @NonNull Builder setFocused(@Nullable Boolean setterArg) {
        this.focused = setterArg;
        return this;
      }

      private @Nullable Long index;

      @CanIgnoreReturnValue
      public @NonNull Builder setIndex(@Nullable Long setterArg) {
        this.index = setterArg;
        return this;
      }

      public @NonNull SelectorMessage build() {
        SelectorMessage pigeonReturn = new SelectorMessage();
        pigeonReturn.setContainsText(containsText);
        pigeonReturn.setClassName(className);
        pigeonReturn.setId(id);
        pigeonReturn.setFocused(focused);
        pigeonReturn.setIndex(index);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(5);
      toListResult.add(containsText);
      toListResult.add(className);
      toListResult.add(id);
      toListResult.add(focused);
      toListResult.add(index);
      return toListResult;
    }

    static @NonNull SelectorMessage fromList(@NonNull ArrayList<Object> list) {
      SelectorMessage pigeonResult = new SelectorMessage();
      Object containsText = list.get(0);
      pigeonResult.setContainsText((String) containsText);
      Object className = list.get(1);
      pigeonResult.setClassName((String) className);
      Object id = list.get(2);
      pigeonResult.setId((id == null) ? null : ((id instanceof Integer) ? (Integer) id : (Long) id));
      Object focused = list.get(3);
      pigeonResult.setFocused((Boolean) focused);
      Object index = list.get(4);
      pigeonResult.setIndex((index == null) ? null : ((index instanceof Integer) ? (Integer) index : (Long) index));
      return pigeonResult;
    }
  }

  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }

  private static class FlutterTestNativeApiCodec extends StandardMessageCodec {
    public static final FlutterTestNativeApiCodec INSTANCE = new FlutterTestNativeApiCodec();

    private FlutterTestNativeApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return SelectorMessage.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof SelectorMessage) {
        stream.write(128);
        writeValue(stream, ((SelectorMessage) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface FlutterTestNativeApi {

    void tap(@NonNull SelectorMessage selector, @NonNull Result<Void> result);

    /** The codec used by FlutterTestNativeApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return FlutterTestNativeApiCodec.INSTANCE;
    }
    /**Sets up an instance of `FlutterTestNativeApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable FlutterTestNativeApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_test_native.FlutterTestNativeApi.tap", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                SelectorMessage selectorArg = (SelectorMessage) args.get(0);
                Result<Void> resultCallback =
                    new Result<Void>() {
                      public void success(Void result) {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.tap(selectorArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
